CREATE TABLE `mdms_tb_deviceinfo` (
  `DEVICE_SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `OWNER_SN` varchar(20) DEFAULT NULL,
  `MANFT` varchar(20) DEFAULT NULL,
  `MODEL` varchar(20) DEFAULT NULL,
  `DEVICE_ID` varchar(100) DEFAULT NULL,
  `OS` varchar(10) DEFAULT NULL,
  `OS_VERSION` varchar(20) DEFAULT NULL,
  `REG_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`DEVICE_SEQ`),
  UNIQUE KEY `OWNER_SN_UNIQUE` (`OWNER_SN`),
  CONSTRAINT `tb_deviceinfo_ibfk_1` FOREIGN KEY (`OWNER_SN`) REFERENCES `tb_userinfo` (`SN`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

CREATE TABLE `mdms_tb_manager` (
  `MANAGER_SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `MANAGER_SN` varchar(20) DEFAULT NULL,
  `MIL_CLASS` varchar(3) DEFAULT NULL,
  PRIMARY KEY (`MANAGER_SEQ`),
  KEY `tb_manager_ibfk_1` (`MANAGER_SN`),
  CONSTRAINT `tb_manager_ibfk_1` FOREIGN KEY (`MANAGER_SN`) REFERENCES `tb_userinfo` (`SN`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `mdms_tb_reason_log` (
  `REASON_SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `USER_SN` varchar(20) NOT NULL,
  `USE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `USE_FUNC` varchar(10) NOT NULL,
  `REASON` varchar(100) NOT NULL,
  `IS_APPROVED` varchar(2) NOT NULL,
  PRIMARY KEY (`REASON_SEQ`),
  KEY `tb_reason_log_ibfk_1` (`USER_SN`),
  CONSTRAINT `tb_reason_log_ibfk_1` FOREIGN KEY (`USER_SN`) REFERENCES `tb_userinfo` (`SN`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

CREATE TABLE `mdms_tb_userinfo` (
  `SN` varchar(20) NOT NULL,
  `NAME` varchar(10) NOT NULL,
  `MIL_CLASS` varchar(3) DEFAULT NULL,
  `UNIT_NAME` varchar(100) DEFAULT NULL,
  `RANK` varchar(10) DEFAULT NULL,
  `PUSHKEY` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`SN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

